from datetime import datetime
from pydantic import BaseModel, Field
from typing import List, Optional, Union
from fastapi import FastAPI

app = FastAPI()
class ItemDetails(BaseModel):
    itemId: Optional[str] = None
    purchasetaxName: Optional[float] = None  # Tax percentage
    taxType: Optional[str] = None  # Can be 'cgst_sgst' or 'igst'
    sgst: Optional[float] = None
    cgst: Optional[float] = None
    igst: Optional[float] = None
    taxAmount: Optional[float] = None

# Define the GRN model
class Outgoing(BaseModel):
    outgoingId: Optional[str] = None
    purchaseOrderId: Optional[str] = None
    grnId : Optional[str] =None
    vendorName: Optional[str] = None
    orderDate: Optional[datetime] = None
    grnDate: Optional[datetime] =None
    receivingLocation: Optional[str] = None
    totalPayableAmount: Optional[float] = None
    comments: Optional[str] = None
    createdDate: Optional[datetime] = None
    lastUpdatedDate:Optional[datetime] = None
    invoiceDate: Optional[datetime] =None
    invoiceNo:Optional[str] =None
    poDate: Optional[datetime] =None
    paymentDate:Optional[datetime] = None
    apinvoiceDate: Optional[datetime] =None
    poCreatedPerson: Optional[str] = None
    grnCreatedPerson: Optional[str] = None
    apCreatedPerson: Optional[str] = None
    grnVerifiedPerson: Optional[str] = None
    apVerifiedPerson: Optional[str] = None
    intimationDays:Optional[int] = None    
    paymentMethod: Optional[str] = None
    paymentMode: Optional[str] = None
    advanceAmount: Optional[float] = None
    totalPrice: Optional[float] = None
    payableAmount:Optional[float] = None 
    partialAmount: Optional[float] = None
    fullPaymentAmount: Optional[float] = None
    paymentType: Optional[str] = None
    chequeNo: Optional[float] = None
    onlinePayment: Optional[float] = None 
    discountDetails: Optional[float] =None
    taxDetails:Optional[float]=None
    neftNo: Optional[str] = None
    rtgsNo: Optional[str] = None
    cashVoucherNo: Optional[str] = None  # New field for voucher number for cash payments
    itemDetails: Optional[List[ItemDetails]] = None  # Include item details here
    status: Optional[str] = None
    contactpersonEmail: Optional[str] = None
    address: Optional[str] = None
    country: Optional[str] = None
    state: Optional[str] = None
    city: Optional[str] = None
    neftNo: Optional[str] = None
    rtgsNo: Optional[str] = None
    impsNo:Optional[str] = None
    upi:Optional[str] = None
    bankName:Optional[str] = None
    paymentCash: Optional[str] = None
    pettyCashAmount:Optional[float] = None
    hoCash:Optional[float] = None
    postalCode: Optional[int] = None
    gstNumber: Optional[str] = None
    paymentTerms: Optional[str] = None
    shippingAddress: Optional[str] = None
    billingAddress: Optional[str] = None
    randomId:Optional[str] = None
    
class OutgoingPost(BaseModel):
    purchaseOrderId: Optional[str] = None
    grnId : Optional[str] =None
    vendorName: Optional[str] = None
    orderDate: Optional[datetime] = None
    invoiceDate: Optional[datetime] =None
    invoiceNo:Optional[str] =None
    grnDate:Optional[datetime] =None
    receivingLocation: Optional[str] = None
    totalPayableAmount: Optional[float] = None
    comments: Optional[str] = None
    createdDate: Optional[datetime] = None
    lastUpdatedDate:Optional[datetime] = None
    paymentDate:Optional[datetime] = None
    poDate: Optional[datetime] =None
    apinvoiceDate: Optional[datetime] =None
    poCreatedPerson: Optional[str] = None
    grnCreatedPerson: Optional[str] = None
    apCreatedPerson: Optional[str] = None
    grnVerifiedPerson: Optional[str] = None
    apVerifiedPerson: Optional[str] = None
    paymentType:Optional[str] = None
    payableAmount:Optional[float] = None
    paymentMethod: Optional[str] = None
    paymentMode: Optional[str] = None
    advanceAmount: Optional[float] = None
    totalPrice: Optional[float] = None
    partialAmount: Optional[float] = None
    fullPaymentAmount: Optional[float] = None
    paymentTerms: Optional[str] = None
    intimationDays:Optional[int] = None
    discountDetails: Optional[float] =None
    taxDetails:Optional[float] = None
    chequeNo: Optional[float] = None
    onlinePayment: Optional[float] = None 
    neftNo: Optional[str] = None
    rtgsNo: Optional[str] = None
    impsNo:Optional[str] = None
    upi:Optional[str] = None
    bankName:Optional[str] = None
    paymentCash: Optional[str] = None
    pettyCashAmount:Optional[float] = None
    hoCash:Optional[float] = None
    itemDetails: Optional[List[ItemDetails]] = None  # Include item details here
    cashVoucherNo: Optional[str] = None  # New field for voucher number for cash payments
    contactpersonEmail: Optional[str] = None
    address: Optional[str] = None
    country: Optional[str] = None
    state: Optional[str] = None
    city: Optional[str] = None
    postalCode: Optional[int] = None
    gstNumber: Optional[str] = None
    shippingAddress: Optional[str] = None
    billingAddress: Optional[str] = None
    status: Optional[str] = None
    randomId:Optional[str] = None